source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'unicorn', '~> 4.8.2'
gem 'pg', '~> 0.17.1'
gem 'carrierwave', '~> 0.10.0'

gem 'enumerize', '~> 0.8.0'

# Authentication
gem 'devise', '~> 3.2.3'

# HTTP
gem 'faraday', '~> 0.9.0'
gem 'faraday_middleware', '~> 0.9.1'

# API / JSON
gem "roar-rails", "~> 0.1.4"
gem "json_spec", "~> 1.1.1"

# View
gem 'gravatar_image_tag', '~> 1.2.0'
gem 'cells', '~> 3.11.1'
gem 'draper', '~> 1.3.0'

# Assets
gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'font-awesome-sass', '~> 4.0.3'
gem 'angular-rails-templates', '~> 0.1.2'

# Development
group :development do
  gem 'guard-livereload', '~> 2.1.2', require: false
  gem 'rack-livereload', '~> 0.3.15'
end

# Testing
group :development, :test do
  gem "rspec-rails", "~> 2.14.1"
  gem "factory_girl_rails", "~> 4.4.1"
end

group :test do
  gem "cucumber-rails", "~> 1.4.0", require: false
  gem "database_cleaner", "~> 1.2.0"
  gem "poltergeist", "~> 1.5.0"
  gem "shoulda-matchers", "~> 2.5.0"
end

