#!/bin/bash
set -e

su -l -p mage <<'EOF'

  npm install -g grunt-cli

  cd /mage && \
    npm install && \
    bundle install

  cd /mage/mage-mobile && \
    grunt build

  cd /mage/mage-table && \
    grunt build

  cd /mage/mage-board && \
    grunt build

  cd /mage/mage-reactive && \
    npm install

EOF

