#!/bin/bash
set -e

chown -R mage:www-data /var/mage/log

# run nginx not as daemon!
# echo "daemon off;" >> /etc/nginx/nginx.conf 
service nginx start

# -p important to preserve the environment (otherwise, docker env variables are lost)
su -l -p mage <<'EOF'

  # Run database migrations
  cd /mage/mage-desktop && \
    RAILS_ENV=production bundle exec rake db:migrate db:seed

  # Precompile assets
  cd /mage/mage-desktop && \
    RAILS_ENV=production bundle exec rake assets:precompile

  # Run kitten, run!
  cd /mage && \
    supervisord -c run.conf

EOF

