source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'unicorn', '~> 4.8.2'
gem 'pg', '~> 0.17.1'

# Authentication
gem 'devise', '~> 3.2.3'

# API / JSON
gem "roar-rails", "~> 0.1.4"
gem "json_spec", "~> 1.1.1"

# Testing
group :development, :test do
  gem "rspec-rails", "~> 2.14.1"
  gem "factory_girl_rails", "~> 4.4.1"
end

group :test do
  gem "cucumber-rails", "~> 1.4.0", require: false
  gem "database_cleaner", "~> 1.2.0"
  gem "poltergeist", "~> 1.5.0"
  gem "shoulda-matchers", "~> 2.5.0"
end

