source 'https://rubygems.org'
ruby '2.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.3'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.17.1'

# Authentication
gem 'devise', '~> 3.2.3'

# Testing
group :development, :test do
  gem "rspec-rails", "~> 2.14.1"
  gem "factory_girl_rails", "~> 4.4.1"
end

group :test do
  gem "cucumber-rails", "~> 1.4.0", require: false
  gem "database_cleaner", "~> 1.2.0"
  gem "poltergeist", "~> 1.5.0"
  gem "shoulda-matchers", "~> 2.5.0"
end
